/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeguii.admin;

import cafeguii.koneksi.koneksi;
import cafeguii.login.Login_admin;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dliyaa'ul
 */
public class Detail_bahan extends javax.swing.JFrame {

    public Detail_bahan() {
        initComponents();
        loadKolom();
        table_detail_bahan.setModel(model);
        conn = koneksi.bukaKoneksi();
        daftarDetailBahan = new ArrayList<>();
        loadDetailBahan();
        tampilDetailBahan();
        populateComboBoxes();
        spn_stok.setValue(0);
        spn_stok.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1)); // Menetapkan nilai minimum
    }

    private DefaultTableModel model = new DefaultTableModel();
    private Connection conn;
    private ArrayList<DetailBahan> daftarDetailBahan;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detail_bahan = new javax.swing.JTable();
        spn_stok = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        cb_nama1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cb_nama2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cb_nama3 = new javax.swing.JComboBox<>();
        label_stokBahan = new javax.swing.JLabel();
        label_stokBahan2 = new javax.swing.JLabel();
        label_stokBahan3 = new javax.swing.JLabel();
        lbl_idDetailBahan = new javax.swing.JLabel();
        cb_bahan = new javax.swing.JComboBox<>();
        btn_produk = new javax.swing.JButton();
        cb_history1 = new javax.swing.JComboBox<>();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Detail Bahan");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Kuantitas");

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(102, 102, 102));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(102, 102, 102));
        btn_edit.setText("Update");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        table_detail_bahan.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        table_detail_bahan.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "IdDetailBahan", "Nama Bahan 1", "Nama Bahan 2", "Nama Bahan 3", "Kuantitas"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        table_detail_bahan.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(table_detail_bahan);

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Nama Bahan 1");

        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(102, 102, 102));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        cb_nama1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cb_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nama1ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Nama Bahan 2");

        cb_nama2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cb_nama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nama2ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Nama Bahan 3");

        cb_nama3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cb_nama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nama3ActionPerformed(evt);
            }
        });

        label_stokBahan.setText("stok : ");

        label_stokBahan2.setText("stok : ");

        label_stokBahan3.setText("stok : ");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
                jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(lbl_idDetailBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(jPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label_stokBahan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_nama1, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54,
                                                        Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout
                                                .createSequentialGroup()
                                                .addGroup(jPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(label_stokBahan2,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 116,
                                                                Short.MAX_VALUE)
                                                        .addComponent(cb_nama2, 0, 119, Short.MAX_VALUE))
                                                .addGap(52, 52, 52)))
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGroup(jPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                                .addComponent(cb_nama3, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGap(26, 26, 26))
                                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel12)
                                                                .addGap(28, 28, 28)))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(spn_stok, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(274, 274, 274))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addComponent(label_stokBahan3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addGap(0, 423, Short.MAX_VALUE)
                                .addComponent(btn_add)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_reset)
                                .addGap(492, 492, 492))
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(443, 443, 443)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        1087, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(30, Short.MAX_VALUE)));
        jPanelLayout.setVerticalGroup(
                jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(0, 79, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
                                                        Short.MAX_VALUE)
                                                .addGroup(jPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel12))))
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cb_nama1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_idDetailBahan))
                                        .addComponent(cb_nama2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spn_stok, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cb_nama3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_stokBahan2)
                                        .addComponent(label_stokBahan)
                                        .addComponent(label_stokBahan3))
                                .addGap(31, 31, 31)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        cb_bahan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_bahan.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Bahan", "Stok Bahan", "Detail Bahan" }));
        cb_bahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bahanActionPerformed(evt);
            }
        });

        btn_produk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_produk.setText("Produk");
        btn_produk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produkActionPerformed(evt);
            }
        });

        cb_history1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_history1.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "History", "History Beli Bahan", "History Penjualan" }));
        cb_history1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_history1ActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_produk, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_bahan, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(cb_history1, 0, 246, Short.MAX_VALUE)
                                        .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1196, 1196, 1196))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(274, 274, 274)
                                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1095,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(79, Short.MAX_VALUE))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(cb_bahan, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_produk)
                                .addGap(27, 27, 27)
                                .addComponent(cb_history1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313,
                                        Short.MAX_VALUE)
                                .addComponent(btn_logout)
                                .addGap(25, 25, 25))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(22, Short.MAX_VALUE))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadKolom() {
        model.addColumn("IdDetailBahan");
        model.addColumn("KodeBahan");
        model.addColumn("KodeBahan2");
        model.addColumn("KodeBahan3");
        model.addColumn("Kuantitas");
    }

    private void loadDetailBahan() {
        try (Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/akubakulcs", "root",
                "Opoae_123")) {
            daftarDetailBahan = new ArrayList<>();
            String kueri = "SELECT db.IdDetailBahan, sb1.NamaBahan AS KodeBahan, sb2.NamaBahan AS KodeBahan2, sb3.NamaBahan AS KodeBahan3, db.Kuantitas "
                    + "FROM detailbahan db "
                    + "JOIN stokbahan sb1 ON db.KodeBahan = sb1.KodeBahan "
                    + "JOIN stokbahan sb2 ON db.KodeBahan2 = sb2.KodeBahan "
                    + "JOIN stokbahan sb3 ON db.KodeBahan3 = sb3.KodeBahan";
            try (PreparedStatement ps = koneksi.prepareStatement(kueri); ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    int IdDetailBahan = rs.getInt("IdDetailBahan");
                    String KodeBahan = rs.getString("KodeBahan");
                    String KodeBahan2 = rs.getString("KodeBahan2");
                    String KodeBahan3 = rs.getString("KodeBahan3");
                    int Kuantitas = rs.getInt("Kuantitas");
                    DetailBahan detailBahan = new DetailBahan(IdDetailBahan, KodeBahan, KodeBahan2, KodeBahan3,
                            Kuantitas);
                    daftarDetailBahan.add(detailBahan);
                    tampilDetailBahan();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Detail_bahan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ubahData(int IdDetailBahan, String kodebahan, String kodebahan2, String kodebahan3, int kuantitas) {
        if (conn != null) {
            try {
                String kueri = "UPDATE detailbahan SET KodeBahan=?, KodeBahan2=?, KodeBahan3=?, Kuantitas=? WHERE IdDetailBahan=?";
                PreparedStatement ps = conn.prepareStatement(kueri);
                ps.setString(1, kodebahan);
                ps.setString(2, kodebahan2);
                ps.setString(3, kodebahan3);
                ps.setInt(4, kuantitas);
                ps.setInt(5, IdDetailBahan);

                int hasil = ps.executeUpdate();
                if (hasil == 1) {
                    JOptionPane.showMessageDialog(this, "Update Berhasil");
                    // Ubah isi tabel
                    loadKolom();
                    loadDetailBahan();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Detail_bahan.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void tampilDetailBahan() {
        model.setRowCount(0);
        for (DetailBahan db : daftarDetailBahan) {
            model.addRow(new Object[] { db.getIdDetailBahan(), db.getKodeBahan(), db.getKodeBahan2(),
                    db.getKodeBahan3(), db.getKuantitas() });
        }
    }

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_addActionPerformed
        String namaBahan1 = (String) cb_nama1.getSelectedItem();
        String namaBahan2 = (String) cb_nama2.getSelectedItem();
        String namaBahan3 = (String) cb_nama3.getSelectedItem();
        int kuantitas = (int) spn_stok.getValue();

        if (btn_add.getText().equals("Submit")) {
            // Periksa apakah ada pilihan yang sama di ketiga JComboBox
            if (namaBahan1.equals(namaBahan2) || namaBahan1.equals(namaBahan3) || namaBahan2.equals(namaBahan3)) {
                JOptionPane.showMessageDialog(this, "Pilih bahan yang berbeda untuk setiap slot.");
                return; // Keluar dari metode jika ada pilihan yang sama
            }

            try (Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/akubakulcs", "root",
                    "Opoae_123")) {
                // Ambil KodeBahan untuk masing-masing namaBahan dari tabel stokbahan
                int kodeBahan1 = getKodeBahan(koneksi, namaBahan1);
                int kodeBahan2 = getKodeBahan(koneksi, namaBahan2);
                int kodeBahan3 = getKodeBahan(koneksi, namaBahan3);

                // Periksa stok untuk setiap bahan yang dipilih
                if (checkStockForBahan(koneksi, kodeBahan1, kuantitas)
                        && checkStockForBahan(koneksi, kodeBahan2, kuantitas)
                        && checkStockForBahan(koneksi, kodeBahan3, kuantitas)) {

                    String kueri = "INSERT INTO detailbahan (KodeBahan, KodeBahan2, KodeBahan3, Kuantitas) VALUES (?,?,?,?)";
                    try (PreparedStatement ps = koneksi.prepareStatement(kueri)) {
                        // Lakukan operasi tambah data menggunakan nilai yang telah dipilih
                        ps.setInt(1, kodeBahan1);
                        ps.setInt(2, kodeBahan2);
                        ps.setInt(3, kodeBahan3);
                        ps.setInt(4, kuantitas);

                        int hasil = ps.executeUpdate();

                        if (hasil > 0) {
                            JOptionPane.showMessageDialog(this, "Data Detail Bahan berhasil ditambahkan.");
                            // Kurangi stok untuk setiap bahan yang dipilih
                            reduceStock(koneksi, kodeBahan1, kuantitas);
                            reduceStock(koneksi, kodeBahan2, kuantitas);
                            reduceStock(koneksi, kodeBahan3, kuantitas);
                            // Memuat ulang data setelah berhasil menambahkan
                            loadDetailBahan();
                            // Reset nilai ComboBox dan JSpinner setelah menambahkan data
                            resetFields();
                        } else {
                            JOptionPane.showMessageDialog(this, "Gagal menambahkan data Detail Bahan.");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Stok tidak mencukupi untuk satu atau lebih bahan yang dipilih.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else if (btn_add.getText().equals("Edit")) {
            int barisTerpilih = table_detail_bahan.getSelectedRow();
            ubahData(daftarDetailBahan.get(barisTerpilih).getIdDetailBahan(), namaBahan1, namaBahan2, namaBahan3,
                    kuantitas);

        }
        resetFields();
    }// GEN-LAST:event_btn_addActionPerformed

    private int getKodeBahan(Connection connection, String namaBahan) throws SQLException {
        String query = "SELECT KodeBahan FROM stokbahan WHERE NamaBahan = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, namaBahan);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getInt("KodeBahan");
                }
            }
        }
        throw new SQLException("Bahan dengan nama '" + namaBahan + "' tidak ditemukan.");
    }

    private boolean checkStockForBahan(Connection connection, int kodeBahan, int kuantitas) throws SQLException {
        String query = "SELECT Stok FROM stokbahan WHERE KodeBahan = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, kodeBahan);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int stok = resultSet.getInt("Stok");
                    // Periksa apakah stok mencukupi untuk kuantitas yang diminta
                    return stok >= kuantitas;
                }
            }
        }
        return false;
    }

    private void reduceStock(Connection connection, int kodeBahan, int kuantitas) throws SQLException {
        String query = "UPDATE stokbahan SET Stok = Stok - ? WHERE KodeBahan = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, kuantitas);
            statement.setInt(2, kodeBahan);
            statement.executeUpdate();
        }
    }

    private void populateComboBoxes() {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/akubakulcs", "root",
                "Opoae_123")) {
            String query = "SELECT NamaBahan FROM stokbahan";
            try (PreparedStatement statement = connection.prepareStatement(query);
                    ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    String namaBahan = resultSet.getString("NamaBahan");
                    cb_nama1.addItem(namaBahan);
                    cb_nama2.addItem(namaBahan);
                    cb_nama3.addItem(namaBahan);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Detail_bahan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetFields() {
        // Reset nilai JComboBox dan JSpinner
        cb_nama1.setSelectedIndex(0);
        cb_nama2.setSelectedIndex(0);
        cb_nama3.setSelectedIndex(0);
        spn_stok.setValue(0);
        label_stokBahan.setText("stok : ");
        label_stokBahan2.setText("stok : ");
        label_stokBahan3.setText("stok : ");
    }

    private void updateStockLabel(JComboBox<String> comboBox, JLabel stockLabel) {
        String selectedBahan = comboBox.getSelectedItem().toString();
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/akubakulcs", "root",
                "Opoae_123")) {
            String query = "SELECT Stok FROM stokbahan WHERE NamaBahan = ?";
            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, selectedBahan);
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        int stok = resultSet.getInt("Stok");
                        stockLabel.setText(String.valueOf(stok));
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Detail_bahan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_editActionPerformed
        int barisTerpilih = table_detail_bahan.getSelectedRow();
        cb_nama1.setSelectedItem(model.getValueAt(barisTerpilih, 1).toString());
        cb_nama2.setSelectedItem(model.getValueAt(barisTerpilih, 2).toString());
        cb_nama3.setSelectedItem(model.getValueAt(barisTerpilih, 3));
        spn_stok.setValue(model.getValueAt(barisTerpilih, 4));
        btn_add.setText("Edit");
    }// GEN-LAST:event_btn_editActionPerformed

    private void updateStok(String namaBahan1, String namaBahan2, String namaBahan3, int selisihKuantitas,
            boolean kurangi, Connection koneksi) throws SQLException {
        // Lakukan perubahan stok untuk masing-masing bahan
        String queryUpdateStok = "UPDATE stokbahan SET Stok = Stok + ? WHERE KodeBahan = ?";
        try (PreparedStatement psUpdateStok = koneksi.prepareStatement(queryUpdateStok)) {
            int perubahan = kurangi ? -selisihKuantitas : selisihKuantitas;
            psUpdateStok.setInt(1, perubahan);
            psUpdateStok.setString(2, namaBahan1);
            psUpdateStok.executeUpdate();

            psUpdateStok.setInt(1, perubahan);
            psUpdateStok.setString(2, namaBahan2);
            psUpdateStok.executeUpdate();

            psUpdateStok.setInt(1, perubahan);
            psUpdateStok.setString(2, namaBahan3);
            psUpdateStok.executeUpdate();
        }
    }

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_resetActionPerformed
        resetFields();
    }// GEN-LAST:event_btn_resetActionPerformed

    private void cb_bahanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cb_bahanActionPerformed
        String selectedItem = (String) cb_bahan.getSelectedItem();

        if ("Stok Bahan".equals(selectedItem)) {
            BahanStock bahan = new BahanStock();
            bahan.setVisible(true);
            this.dispose();
        } else if ("Detail Bahan".equals(selectedItem)) {
            Detail_bahan detail_bahan = new Detail_bahan();
            detail_bahan.setVisible(true);
            this.dispose();
        }
        this.dispose();
    }// GEN-LAST:event_cb_bahanActionPerformed

    private void btn_produkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_produkActionPerformed
        ProdukManagement produk = new ProdukManagement();
        produk.setVisible(true);

        // Menutup Jframe dashboard saat ini
        this.dispose();
    }// GEN-LAST:event_btn_produkActionPerformed

    private void cb_history1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cb_history1ActionPerformed
        String selectedItem = (String) cb_history1.getSelectedItem();

        if ("History Beli Bahan".equals(selectedItem)) {
            History_pembelian pembelian = new History_pembelian();
            pembelian.setVisible(true);
            this.dispose();
        } else if ("History Penjualan".equals(selectedItem)) {
            History_penjualan penjualan = new History_penjualan();
            penjualan.setVisible(true);
            this.dispose();
        }

        this.dispose();
    }// GEN-LAST:event_cb_history1ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();

        Login_admin login = new Login_admin();
        login.setVisible(true);
    }// GEN-LAST:event_btn_logoutActionPerformed

    private void cb_nama1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cb_nama1ActionPerformed
        updateStockLabel(cb_nama1, label_stokBahan);
    }// GEN-LAST:event_cb_nama1ActionPerformed

    private void cb_nama2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cb_nama2ActionPerformed
        updateStockLabel(cb_nama2, label_stokBahan2);
    }// GEN-LAST:event_cb_nama2ActionPerformed

    private void cb_nama3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cb_nama3ActionPerformed
        updateStockLabel(cb_nama3, label_stokBahan3);
    }// GEN-LAST:event_cb_nama3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_bahan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_bahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_produk;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> cb_bahan;
    private javax.swing.JComboBox<String> cb_history1;
    private javax.swing.JComboBox<String> cb_nama1;
    private javax.swing.JComboBox<String> cb_nama2;
    private javax.swing.JComboBox<String> cb_nama3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_stokBahan;
    private javax.swing.JLabel label_stokBahan2;
    private javax.swing.JLabel label_stokBahan3;
    private javax.swing.JLabel lbl_idDetailBahan;
    private javax.swing.JSpinner spn_stok;
    private javax.swing.JTable table_detail_bahan;
    // End of variables declaration//GEN-END:variables
}
